# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joey/Documents/projects/engine-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joey/Documents/projects/engine-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/Documents/projects/engine-1/CMakeFiles /home/joey/Documents/projects/engine-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/Documents/projects/engine-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cengine-1

# Build rule for target.
cengine-1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cengine-1
.PHONY : cengine-1

# fast build rule for target.
cengine-1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/build
.PHONY : cengine-1/fast

#=============================================================================
# Target rules for targets named sengine-1

# Build rule for target.
sengine-1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sengine-1
.PHONY : sengine-1

# fast build rule for target.
sengine-1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/build
.PHONY : sengine-1/fast

src/client/cmain.o: src/client/cmain.c.o

.PHONY : src/client/cmain.o

# target to build an object file
src/client/cmain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cmain.c.o
.PHONY : src/client/cmain.c.o

src/client/cmain.i: src/client/cmain.c.i

.PHONY : src/client/cmain.i

# target to preprocess a source file
src/client/cmain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cmain.c.i
.PHONY : src/client/cmain.c.i

src/client/cmain.s: src/client/cmain.c.s

.PHONY : src/client/cmain.s

# target to generate assembly for a file
src/client/cmain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cmain.c.s
.PHONY : src/client/cmain.c.s

src/client/cnetwork.o: src/client/cnetwork.c.o

.PHONY : src/client/cnetwork.o

# target to build an object file
src/client/cnetwork.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cnetwork.c.o
.PHONY : src/client/cnetwork.c.o

src/client/cnetwork.i: src/client/cnetwork.c.i

.PHONY : src/client/cnetwork.i

# target to preprocess a source file
src/client/cnetwork.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cnetwork.c.i
.PHONY : src/client/cnetwork.c.i

src/client/cnetwork.s: src/client/cnetwork.c.s

.PHONY : src/client/cnetwork.s

# target to generate assembly for a file
src/client/cnetwork.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/cnetwork.c.s
.PHONY : src/client/cnetwork.c.s

src/client/input.o: src/client/input.c.o

.PHONY : src/client/input.o

# target to build an object file
src/client/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/input.c.o
.PHONY : src/client/input.c.o

src/client/input.i: src/client/input.c.i

.PHONY : src/client/input.i

# target to preprocess a source file
src/client/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/input.c.i
.PHONY : src/client/input.c.i

src/client/input.s: src/client/input.c.s

.PHONY : src/client/input.s

# target to generate assembly for a file
src/client/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/input.c.s
.PHONY : src/client/input.c.s

src/client/render.o: src/client/render.c.o

.PHONY : src/client/render.o

# target to build an object file
src/client/render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/render.c.o
.PHONY : src/client/render.c.o

src/client/render.i: src/client/render.c.i

.PHONY : src/client/render.i

# target to preprocess a source file
src/client/render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/render.c.i
.PHONY : src/client/render.c.i

src/client/render.s: src/client/render.c.s

.PHONY : src/client/render.s

# target to generate assembly for a file
src/client/render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/client/render.c.s
.PHONY : src/client/render.c.s

src/common/cfg.o: src/common/cfg.c.o

.PHONY : src/common/cfg.o

# target to build an object file
src/common/cfg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/cfg.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/cfg.c.o
.PHONY : src/common/cfg.c.o

src/common/cfg.i: src/common/cfg.c.i

.PHONY : src/common/cfg.i

# target to preprocess a source file
src/common/cfg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/cfg.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/cfg.c.i
.PHONY : src/common/cfg.c.i

src/common/cfg.s: src/common/cfg.c.s

.PHONY : src/common/cfg.s

# target to generate assembly for a file
src/common/cfg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/cfg.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/cfg.c.s
.PHONY : src/common/cfg.c.s

src/common/common.o: src/common/common.c.o

.PHONY : src/common/common.o

# target to build an object file
src/common/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/common.c.o
.PHONY : src/common/common.c.o

src/common/common.i: src/common/common.c.i

.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/common.c.i
.PHONY : src/common/common.c.i

src/common/common.s: src/common/common.c.s

.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/common.c.s
.PHONY : src/common/common.c.s

src/common/entity.o: src/common/entity.c.o

.PHONY : src/common/entity.o

# target to build an object file
src/common/entity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/entity.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/entity.c.o
.PHONY : src/common/entity.c.o

src/common/entity.i: src/common/entity.c.i

.PHONY : src/common/entity.i

# target to preprocess a source file
src/common/entity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/entity.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/entity.c.i
.PHONY : src/common/entity.c.i

src/common/entity.s: src/common/entity.c.s

.PHONY : src/common/entity.s

# target to generate assembly for a file
src/common/entity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/entity.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/entity.c.s
.PHONY : src/common/entity.c.s

src/common/file.o: src/common/file.c.o

.PHONY : src/common/file.o

# target to build an object file
src/common/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/file.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/file.c.o
.PHONY : src/common/file.c.o

src/common/file.i: src/common/file.c.i

.PHONY : src/common/file.i

# target to preprocess a source file
src/common/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/file.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/file.c.i
.PHONY : src/common/file.c.i

src/common/file.s: src/common/file.c.s

.PHONY : src/common/file.s

# target to generate assembly for a file
src/common/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/file.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/file.c.s
.PHONY : src/common/file.c.s

src/common/insane.o: src/common/insane.c.o

.PHONY : src/common/insane.o

# target to build an object file
src/common/insane.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/insane.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/insane.c.o
.PHONY : src/common/insane.c.o

src/common/insane.i: src/common/insane.c.i

.PHONY : src/common/insane.i

# target to preprocess a source file
src/common/insane.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/insane.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/insane.c.i
.PHONY : src/common/insane.c.i

src/common/insane.s: src/common/insane.c.s

.PHONY : src/common/insane.s

# target to generate assembly for a file
src/common/insane.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/insane.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/insane.c.s
.PHONY : src/common/insane.c.s

src/common/log.o: src/common/log.c.o

.PHONY : src/common/log.o

# target to build an object file
src/common/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/log.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/log.c.o
.PHONY : src/common/log.c.o

src/common/log.i: src/common/log.c.i

.PHONY : src/common/log.i

# target to preprocess a source file
src/common/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/log.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/log.c.i
.PHONY : src/common/log.c.i

src/common/log.s: src/common/log.c.s

.PHONY : src/common/log.s

# target to generate assembly for a file
src/common/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/log.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/log.c.s
.PHONY : src/common/log.c.s

src/common/lua_common.o: src/common/lua_common.c.o

.PHONY : src/common/lua_common.o

# target to build an object file
src/common/lua_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_common.c.o
.PHONY : src/common/lua_common.c.o

src/common/lua_common.i: src/common/lua_common.c.i

.PHONY : src/common/lua_common.i

# target to preprocess a source file
src/common/lua_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_common.c.i
.PHONY : src/common/lua_common.c.i

src/common/lua_common.s: src/common/lua_common.c.s

.PHONY : src/common/lua_common.s

# target to generate assembly for a file
src/common/lua_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_common.c.s
.PHONY : src/common/lua_common.c.s

src/common/lua_sandbox.o: src/common/lua_sandbox.c.o

.PHONY : src/common/lua_sandbox.o

# target to build an object file
src/common/lua_sandbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_sandbox.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_sandbox.c.o
.PHONY : src/common/lua_sandbox.c.o

src/common/lua_sandbox.i: src/common/lua_sandbox.c.i

.PHONY : src/common/lua_sandbox.i

# target to preprocess a source file
src/common/lua_sandbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_sandbox.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_sandbox.c.i
.PHONY : src/common/lua_sandbox.c.i

src/common/lua_sandbox.s: src/common/lua_sandbox.c.s

.PHONY : src/common/lua_sandbox.s

# target to generate assembly for a file
src/common/lua_sandbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/lua_sandbox.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/lua_sandbox.c.s
.PHONY : src/common/lua_sandbox.c.s

src/common/network.o: src/common/network.c.o

.PHONY : src/common/network.o

# target to build an object file
src/common/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/network.c.o
.PHONY : src/common/network.c.o

src/common/network.i: src/common/network.c.i

.PHONY : src/common/network.i

# target to preprocess a source file
src/common/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/network.c.i
.PHONY : src/common/network.c.i

src/common/network.s: src/common/network.c.s

.PHONY : src/common/network.s

# target to generate assembly for a file
src/common/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/network.c.s
.PHONY : src/common/network.c.s

src/common/obj.o: src/common/obj.c.o

.PHONY : src/common/obj.o

# target to build an object file
src/common/obj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/obj.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/obj.c.o
.PHONY : src/common/obj.c.o

src/common/obj.i: src/common/obj.c.i

.PHONY : src/common/obj.i

# target to preprocess a source file
src/common/obj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/obj.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/obj.c.i
.PHONY : src/common/obj.c.i

src/common/obj.s: src/common/obj.c.s

.PHONY : src/common/obj.s

# target to generate assembly for a file
src/common/obj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/obj.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/obj.c.s
.PHONY : src/common/obj.c.s

src/common/str.o: src/common/str.c.o

.PHONY : src/common/str.o

# target to build an object file
src/common/str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/str.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/str.c.o
.PHONY : src/common/str.c.o

src/common/str.i: src/common/str.c.i

.PHONY : src/common/str.i

# target to preprocess a source file
src/common/str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/str.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/str.c.i
.PHONY : src/common/str.c.i

src/common/str.s: src/common/str.c.s

.PHONY : src/common/str.s

# target to generate assembly for a file
src/common/str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/str.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/str.c.s
.PHONY : src/common/str.c.s

src/common/vfs.o: src/common/vfs.c.o

.PHONY : src/common/vfs.o

# target to build an object file
src/common/vfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/vfs.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/vfs.c.o
.PHONY : src/common/vfs.c.o

src/common/vfs.i: src/common/vfs.c.i

.PHONY : src/common/vfs.i

# target to preprocess a source file
src/common/vfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/vfs.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/vfs.c.i
.PHONY : src/common/vfs.c.i

src/common/vfs.s: src/common/vfs.c.s

.PHONY : src/common/vfs.s

# target to generate assembly for a file
src/common/vfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cengine-1.dir/build.make CMakeFiles/cengine-1.dir/src/common/vfs.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/common/vfs.c.s
.PHONY : src/common/vfs.c.s

src/server/smain.o: src/server/smain.c.o

.PHONY : src/server/smain.o

# target to build an object file
src/server/smain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/smain.c.o
.PHONY : src/server/smain.c.o

src/server/smain.i: src/server/smain.c.i

.PHONY : src/server/smain.i

# target to preprocess a source file
src/server/smain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/smain.c.i
.PHONY : src/server/smain.c.i

src/server/smain.s: src/server/smain.c.s

.PHONY : src/server/smain.s

# target to generate assembly for a file
src/server/smain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/smain.c.s
.PHONY : src/server/smain.c.s

src/server/snetwork.o: src/server/snetwork.c.o

.PHONY : src/server/snetwork.o

# target to build an object file
src/server/snetwork.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/snetwork.c.o
.PHONY : src/server/snetwork.c.o

src/server/snetwork.i: src/server/snetwork.c.i

.PHONY : src/server/snetwork.i

# target to preprocess a source file
src/server/snetwork.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/snetwork.c.i
.PHONY : src/server/snetwork.c.i

src/server/snetwork.s: src/server/snetwork.c.s

.PHONY : src/server/snetwork.s

# target to generate assembly for a file
src/server/snetwork.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sengine-1.dir/build.make CMakeFiles/sengine-1.dir/src/server/snetwork.c.s
.PHONY : src/server/snetwork.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cengine-1"
	@echo "... sengine-1"
	@echo "... src/client/cmain.o"
	@echo "... src/client/cmain.i"
	@echo "... src/client/cmain.s"
	@echo "... src/client/cnetwork.o"
	@echo "... src/client/cnetwork.i"
	@echo "... src/client/cnetwork.s"
	@echo "... src/client/input.o"
	@echo "... src/client/input.i"
	@echo "... src/client/input.s"
	@echo "... src/client/render.o"
	@echo "... src/client/render.i"
	@echo "... src/client/render.s"
	@echo "... src/common/cfg.o"
	@echo "... src/common/cfg.i"
	@echo "... src/common/cfg.s"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/common/entity.o"
	@echo "... src/common/entity.i"
	@echo "... src/common/entity.s"
	@echo "... src/common/file.o"
	@echo "... src/common/file.i"
	@echo "... src/common/file.s"
	@echo "... src/common/insane.o"
	@echo "... src/common/insane.i"
	@echo "... src/common/insane.s"
	@echo "... src/common/log.o"
	@echo "... src/common/log.i"
	@echo "... src/common/log.s"
	@echo "... src/common/lua_common.o"
	@echo "... src/common/lua_common.i"
	@echo "... src/common/lua_common.s"
	@echo "... src/common/lua_sandbox.o"
	@echo "... src/common/lua_sandbox.i"
	@echo "... src/common/lua_sandbox.s"
	@echo "... src/common/network.o"
	@echo "... src/common/network.i"
	@echo "... src/common/network.s"
	@echo "... src/common/obj.o"
	@echo "... src/common/obj.i"
	@echo "... src/common/obj.s"
	@echo "... src/common/str.o"
	@echo "... src/common/str.i"
	@echo "... src/common/str.s"
	@echo "... src/common/vfs.o"
	@echo "... src/common/vfs.i"
	@echo "... src/common/vfs.s"
	@echo "... src/server/smain.o"
	@echo "... src/server/smain.i"
	@echo "... src/server/smain.s"
	@echo "... src/server/snetwork.o"
	@echo "... src/server/snetwork.i"
	@echo "... src/server/snetwork.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

